# contexts

greetings:
  enter: |
    echo "Hello $USER! The current date is $(date) and you are in $(pwd)."
  exit: echo "Session finished at $(date)"

work:
  use:
    - base-history
    - base-bye
    - greetings
  enter: |
    echo "Warning, session history will be stored at $HISTFILE"

# bases

base-history:
  enter: |
    mkdir -p $HOME/.shctx/$SHCTX_CONTEXT
    export HISTFILE="$HOME/.shctx/$SHCTX_CONTEXT/history"

base-bye:
  exit:
    echo bye bye!
