default:
  enter: |-
    date
    pwd
    mkdir -p $HOME/.shctx/$SHCTX_CONTEXT
    export HISTFILE="$HOME/.shctx/$SHCTX_CONTEXT/history"
  exit: echo bye bye!
qwer:
  enter: |-
    date
    pwd
    mkdir -p $HOME/.shctx/$SHCTX_CONTEXT
    export HISTFILE="$HOME/.shctx/$SHCTX_CONTEXT/history"
  exit: echo bye bye!
rio:
  enter: |-
    date
    cd $HOME/rio
    pwd
    la
    mkdir -p $HOME/.shctx/$SHCTX_CONTEXT
    export HISTFILE="$HOME/.shctx/$SHCTX_CONTEXT/history"
  exit: echo bye bye!
shctx:
  enter: |-
    date
    cd $HOME/rio/shctx
    pwd
    la
    mkdir -p $HOME/.shctx/$SHCTX_CONTEXT
    export HISTFILE="$HOME/.shctx/$SHCTX_CONTEXT/history"
  exit: echo bye bye!
